services:
 mysql-server:
  image: "${MYSQL_IMAGE}:${MYSQL_IMAGE_TAG}"
  command:
   - mysqld
   - --skip-mysqlx
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
# Only during upgrade from versions prior 6.4 and new installations (schema deployment)
   - --log_bin_trust_function_creators=1
# Use TLS encryption for connections to database
#   - --require-secure-transport
#   - --ssl-ca=/run/secrets/root-ca.pem
#   - --ssl-cert=/run/secrets/server-cert.pem
#   - --ssl-key=/run/secrets/server-key.pem
  restart: "${RESTART_POLICY}"
  attach: false
  volumes:
   - ${DATA_DIRECTORY}/var/lib/mysql:/var/lib/mysql:rw
   - ${ENV_VARS_DIRECTORY}/mysql_init/init_proxy_db.sql:/docker-entrypoint-initdb.d/mysql_init_proxy.sql:ro
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_mysql
   - path: ${ENV_VARS_DIRECTORY}/.env_db_mysql_override
     required: false
  environment:
   - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
#   - server-key.pem
#   - server-cert.pem
#   - root-ca.pem
  stop_grace_period: 1m
  networks:
   database:
    aliases:
     - mysql-server

 db-data-mysql:
  image: busybox
  volumes:
   - ${DATA_DIRECTORY}/var/lib/mysql:/var/lib/mysql:rw

 elasticsearch:
  image: "${ELASTICSEARCH_IMAGE}:${ELASTICSEARCH_IMAGE_TAG}"
  restart: "${RESTART_POLICY}"
  attach: false
  profiles:
   - elasticsearch
  environment:
   - transport.host=0.0.0.0
   - discovery.zen.minimum_master_nodes=1
  networks:
   database:
    aliases:
     - elasticsearch
